# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(null=True, verbose_name='最后登陆时间'),
        ),
    ]
