# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_auto_20171209_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=True, verbose_name='活跃状态'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='未命名', max_length=20, verbose_name='房间名称'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_uid',
            field=models.IntegerField(default=0, verbose_name='房间号'),
        ),
    ]
