# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_auto_20171209_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_password',
            field=models.CharField(max_length=120, null=True, verbose_name='房间密码'),
        ),
    ]
