# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_room_room_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_uid',
            field=models.CharField(default='0', max_length=240, verbose_name='房间号'),
        ),
    ]
