# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_room_room_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_uid',
        ),
    ]
