# Generated by Django 2.0 on 2017-12-28 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0005_remove_room_room_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatroom.User', verbose_name='发送信息的用户'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatroom.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='master', to='chatroom.User', verbose_name='房主'),
        ),
    ]
