# Generated by Django 2.0 on 2017-12-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0006_auto_20171228_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='房间名称'),
        ),
    ]
